### ISSUE TITLE
not show ean on product info page

### ISSUE THREAD

**Issue by centoasa** [numinix/numinix_product_fields#6]
all configuration is done and OK, but on product page in admin, after insert ean code in filed, ceck again ean doon't show. So also on catalog product info page.

**Comment by jefflew** [comment]
The EAN field hasn't been programmed to show on the product info.  You will need a programmer to set that up for you.  If it's also not storing in the admin, the plugin may not be installed correctly.

**Comment by centoasa** [comment]
Ean code stored on db but not show on admin product page.  What barcode is possible to show on product page?

**Comment by scottfellnuminix** [comment]
UPC can be shown on the product page.  Your programmer can duplicate that
code for EAN.

**Comment by centoasa** [comment]
on my product info page I've add (as you suggest):
<?php echo (($flag_show_product_info_upc == 1 and $products_upc != '') ? '<li>' . TEXT_PRODUCTS_UPC . $products_upc . '</li>' : '') . "\n"; ?>  
but nothing appear

**Comment by jefflew** [comment]
Do you have the UPC field populated in the admin and enabled in your
product layout?

On Fri, Dec 18, 2015 at 2:41 PM, Remigio <notifications@github.com> wrote:

> on my product info page I've add (as you suggest):
> <?php echo (($flag_show_product_info_upc == 1 and $products_upc != '') ? '
> - ' . TEXT_PRODUCTS_UPC . $products_upc . '' : '') . "\n"; ?>
>
> but nothing appear
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numinix/numinix_product_fields/issues/6#issuecomment-165913365>
> .
>



-- 

*Jeff Lew*
President

*Phone:* 1-855-686-4649 Ext 700
*Email/Gchat:* jlew@numinix.com
*Skype:* numinix
[image: Numinix] <http://www.numinix.com/>

[image: Facebook] <http://www.facebook.com/numinix> [image: Twitter]
<http://twitter.com/numinix> [image: Google+]
<https://plus.google.com/+Numinix> [image: Instagram]
<http://instagram.com/numinixwebdev> [image: Pinterest]
<http://www.pinterest.com/numinix> [image: Blog]
<http://www.numinix.com/blog/?feed=rss2>

**Comment by centoasa** [comment]
the strange are these: on my db there is products_upc with code; but into admin-->product this code don't appear. So also on product info page 
http://www.100asa.it/cisco-pa100-alimentatore-spa962-942-922-941-p-2378.html
